### ISSUE TITLE
Some docs issues

### ISSUE THREAD

**Issue by tertsdiepraam** [uutils/coreutils#5692]
I'm going through all signatures for the argument parser. I found some issues in the docs:

- `join` should be `join [OPTION]... FILE1 FILE2`
- `cut` should be `cut OPTION... [FILE]...`
- `mkdir` should be `mkdir [OPTION]... DIRECTORY...` (for some reason it says `[USER]` now 😄 )
- The usage string for everything based on `hashsum` are missing.
- `more` now says `more [OPTIONS] <FILE>...` which matches `util-linux` but uses a different syntax than GNU, which would be `more [OPTIONS]... FILE...`
- `nohup FLAG` should be `nohup OPTION`
- `pr` should be `pr [OPTION]... [FILE]...`
- `printenv` should be `printenv [OPTION]... [VARIABLE]...`
- `printf` should have the strings `printf FORMAT [ARGUMENT]...` and `printf OPTION`
- `basenc` has a `"` at the end of the usage string that shouldn't be there.
- `runcon` has `";` at the end of the usage string that shouldn't be there.
- `shuf` has `;` at the end of the usage string that shouldn't be there.
- `sum` has `"` at the end of the usage string that shouldn't be there.
- The last three lines of `test`'s usage string should be written with `[` instead of `test`.
- `uniq` should be `uniq [OPTION]... [INPUT [OUTPUT]]`
- `unlink` should be `unlink FILE` and `unlink OPTION`
- `vdir` is missing documentation

**Comment by ankit-pn** [comment]
hey i want to work on this, it would be great if you assign this to me!

**Comment by cakebaker** [comment]
@ankit-pn @dvalere already fixed most of the issues in https://github.com/uutils/coreutils/pull/5696, but feel free to work on the remaining issues

**Comment by tertsdiepraam** [comment]
I've made the list into checkmarks to keep track of all the pages that are correct now.

**Comment by zaira-bibi** [comment]
Hi @tertsdiepraam! I would like to work on the remaining issues in the docs.

**Comment by tertsdiepraam** [comment]
@zaira-bibi feel free to! You can mention me in the PRs that you make to ensure I'll see them.

**Comment by zaira-bibi** [comment]
Thanks! I went through the checklist and the repo and it seems like all the issues have been fixed. Kindly let me know if I'm wrong.

**Comment by rwdj** [comment]
Went through the list and found inconsistencies for unlink and runcon.

runcon uutils:

    runcon [CONTEXT COMMAND [ARG...]]

runcon requires a context command to function:

    runcon: No command is specified

unlink uutils:

    unlink [FILE]

unlink requires a file to unlink

    error: the following required arguments were not provided:
      <FILE>

Every other tool matches. I don't have GNU hashsum to check, but it does have a usage string.

**Comment by tertsdiepraam** [comment]
> I don't have GNU hashsum to check, but it does have a usage string.

That's right, because it doesn't exist :)

>  The usage string for everything based on hashsum are missing.

This is still an issue for everything that uses hashsum under the hood like `sha224sum`.

The `test` lines also need to be fixed still, I think.

**Comment by Its-Just-Nans** [comment]
Hi


> This is still an issue for everything that uses hashsum under the hood like sha224sum.

Is this still valid?

```
#!/bin/bash

for i in md5sum sha1sum sha224sum sha256sum sha384sum sha512sum sha3sum sha3-224sum sha3-256sum sha3-384sum sha3-512sum shake128sum shake256sum b2sum b3sum; do
    cargo run $i -h 2>&1 | grep Usage
done
```


```
Usage: target/debug/coreutils md5sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha1sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha224sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha256sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha384sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha512sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-224sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-256sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-384sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-512sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils shake128sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils shake256sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils b2sum --<digest> [OPTIONS]... [FILE]...
Usage: target/debug/coreutils b3sum --<digest> [OPTIONS]... [FILE]...
```


And also

> The test lines also need to be fixed still, I think.


```
cargo run [  --help

Check file types and compare values.

Usage: test EXPRESSION
       [
       [ EXPRESSION ]
       [ ]
       [ OPTION
       ]

Options:
  -h, --help     Print help
  -V, --version  Print version
....
```


This issue is closeable no ?

**Comment by tertsdiepraam** [comment]
It still doesn't work online I think: https://uutils.github.io/coreutils/docs/utils/sha256sum.html

(Unless that has been fixed since the last release and I missed that)

**Comment by Its-Just-Nans** [comment]
Hi

With #7936 

```sh
Usage: target/debug/coreutils md5sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha1sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha224sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha256sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha384sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha512sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-224sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-256sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-384sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils sha3-512sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils shake128sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils shake256sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils b2sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils b3sum [OPTIONS]... [FILE]...
Usage: target/debug/coreutils hashsum --<digest> [OPTIONS]... [FILE]...
```

**Comment by memark** [comment]
>The last three lines of test's usage string should be written with [ instead of test.

It looks like this is now indeed fixed in `main` and could be ticket off:

```sh
$ cargo run -q -- [ --help
Check file types and compare values.

Usage: test EXPRESSION
       test
       [ EXPRESSION ]
       [ ]
       [ OPTION ]
```

**Comment by Its-Just-Nans** [comment]
> It looks like this is now indeed fixed in `main` and could be ticket off:

Hi

I'm not sure about it
- the man page is not correct
- the last line `[ OPTION ]` should be `[ OPTION`
- https://github.com/uutils/coreutils/pull/7936
