### ISSUE TITLE
date: Does not accept decimal offsets

### ISSUE THREAD

**Issue by waveform80** [uutils/coreutils#8618]
Discovered while testing the motd scripts in Ubuntu questing under rust-coreutils. Under gnu-coreutils:

```sh
$ gnudate -d "now - 20 seconds" +%s
1757632916
$ gnudate -d "now - 20.1 seconds" +%s
1757632918
```

Under rust-coreutils:

```sh
$ date -d "now - 20 seconds" +%s
1757632958
$ date -d "now - 20.1 seconds" +%s
date: invalid date 'now - 20.1 seconds'
```

**Comment by yuankunzhang** [comment]
This issue has been fixed in the latest version of parse_datetime.

See https://github.com/uutils/parse_datetime/blob/a4c29bafcb1529d172ace3dacb8db2213a49fbb4/src/items/relative.rs#L141

**Comment by jepler** [comment]
Suggest closing this issue?

**Comment by cakebaker** [comment]
The example from @waveform80 still fails on `main` with the most recent `parse_datetime` version (`0.13.1`):
```
$ cargo run -q date -d "now - 20.1 seconds" +%s
date: invalid date 'now - 20.1 seconds'
```

**Comment by 3v1n0** [comment]
The problem was the space, in fact `date -d "now+1.0 seconds" +%s` works fine.

Fixed in https://github.com/uutils/parse_datetime/pull/246
