### ISSUE TITLE
cksum: Figure out the use of `--binary` on Windows

### ISSUE THREAD

**Issue by RenjiSann** [uutils/coreutils#9168]
Quoting `info '(coreutils) md5sum invocation'`:

>‘-b’
>‘--binary’
>     Treat each input file as binary, by reading it in binary mode and
>     outputting a ‘*’ flag.  This is the inverse of ‘--text’.  On
>     systems like GNU that do not distinguish between binary and text
>     files, this option merely flags each input mode as binary: the MD5
>     checksum is unaffected.  This option is the default on systems like
>     MS-DOS that distinguish between binary and text files, except for
>     reading standard input when standard input is a terminal.

and quoting [Windows' documentation]()

> In text mode, carriage return-line feed (CRLF) combinations are translated into single line feed (LF) characters on input, and LF characters are translated to CRLF combinations on output. When a Unicode stream-I/O function operates in text mode (the default), the source or destination stream is assumed to be a sequence of multibyte characters. Therefore, the Unicode stream-input functions convert multibyte characters to wide characters (as if by a call to the mbtowc function). For the same reason, the Unicode stream-output functions convert wide characters to multibyte characters (as if by a call to the wctomb function).

So I expect that on Windows, when I open a file that contains CRLFs in text mode, I have a different checksum than when I use --binary,
which I could not witness: 

```
$ md5sum --version
md5sum (GNU coreutils) 8.32
Copyright (C) 2020 Free Software Foundation, Inc.

$ xxd my_test
00000000: 7465 7374 0d0a 7465 7374                 test..test # CRLF File
$ xxd my_test2
00000000: 7465 7374 0a74 6573 74                   test.test  # LF File

```

# CRLF File
```
$ md5sum my_test
76ce9f441de2ed5de337d391ad4516b7 *my_test
$ md5sum my_test --binary
76ce9f441de2ed5de337d391ad4516b7 *my_test
$ md5sum my_test --text
76ce9f441de2ed5de337d391ad4516b7  my_test  # I would have expected this hash to be different

$ coreutils.exe hashsum --md5 my_test
76ce9f441de2ed5de337d391ad4516b7 *my_test
$ coreutils.exe hashsum --md5 my_test --binary
76ce9f441de2ed5de337d391ad4516b7 *my_test
$ coreutils.exe hashsum --md5 my_test --text
be778b473235e210cc577056226536a4  my_test # Like this one

```

# LF File
```
$.md5sum my_test2
be778b473235e210cc577056226536a4 *my_test2
$ md5sum my_test2 --binary
be778b473235e210cc577056226536a4 *my_test2
$ md5sum my_test2 --text
be778b473235e210cc577056226536a4  my_test2 # This I expect

$ coreutils.exe hashsum --md5 my_test2
be778b473235e210cc577056226536a4 *my_test2
$ coreutils.exe hashsum --md5 my_test2 --binary
be778b473235e210cc577056226536a4 *my_test2
$ coreutils.exe hashsum --md5 my_test2 --text
be778b473235e210cc577056226536a4  my_test2 # Like this one
```

So several reasons could justify this problem:
1) My Windows setup is flawed and I have a skill issue preventing me to witness the desired behavior
2) The version of coreutils I could get my hands for Windows is too old
3) I misunderstood the documentation
4) There is a bug in GNU's coreutils

**Comment by RenjiSann** [comment]
Maybe you'd have an input about that @pixelb ?

**Comment by pixelb** [comment]
@RenjiSann your understanding matches mine.
Where did you get the windows coreutils build?
Note if it's WSL that'd be using the UNIX interface and so there'd be no difference in text/binary

**Comment by oech3** [comment]
I don't think coreutils supports Win officially. But you can DL binaries for cygwin: https://packages.msys2.org/packages/coreutils?variant=x86_64

**Comment by RenjiSann** [comment]
> I don't think coreutils supports Win officially. But you can DL binaries for cygwin: https://packages.msys2.org/packages/coreutils?variant=x86_64

That's the one I used

**Comment by oech3** [comment]
Can GNU just drop text mode if it is not used by anyone?
@lazka Is MSYS2 depending on `md5sum --text`?

**Comment by pixelb** [comment]
Ok I'll have a look as it does look like a GNU bug.
I see '*' is being output by default so that part is correct on windows at least.

**Comment by pixelb** [comment]
@oech3 The newer consolidated cksum command that's replaced the deprecated legacy separated commands, doesn't document the --text and --binary options, only supporting them to allow emulation of the older separated commands. Indeed those options are just confusing and should never have been included, so cksum took the opportunity to not support them

**Comment by oech3** [comment]
Oops. This project is planning to move every flags from `hashsum` to `cksum` (including `--text`?) before dropping it which could cause confusion again.

**Comment by pixelb** [comment]
From a quick search I think I see the issue with GNU on windows. You said it's an msys build and fopen() on msys defaults to binary mode, whereas GNU only explicitly sets "rb" mode, expecting the other default. 

@RenjiSann 
I think you can change the default with CYGWIN=textmode in the environment.
I'm guessing that would make GNU match hashsum's output.

I suppose GNU *sum could set that environment variable internally with --text

**Comment by pixelb** [comment]
> Oops. This project is planning to move every flags from `hashsum` to `cksum` (including `--text`?) before dropping it which could cause confusion again.

@oech3 To clarify, GNU cksum does actually support --text and --binary, so that cksum can emulate the legacy standalone checksumming utilities with a wrapper script if desired. However those options are deprecated for new uses, so therefore cksum --help (or man page) does not document those options.

**Comment by oech3** [comment]
I see (and I noiced that uu-cksum does it already)

**Comment by RenjiSann** [comment]
> I think you can change the default with CYGWIN=textmode in the environment.
I'm guessing that would make GNU match hashsum's output.

Didn't do anything on my side, not sure if I'm missing something


So I'm not sure what to do here. Should we implement the --text/--binary feature at all on windows ?

**Comment by pixelb** [comment]
@RenjiSann It really is debatable whether --text, --binary is useful at all,
and as I mentioned, GNU cksum has deprecated those options and doesn't document then in --help or man page.
Anyway https://github.com/coreutils/coreutils/issues/123#issuecomment-3502409576 should fix the issue for GNU I think, though I'm surprised `CYGWIN=textmode` doesn't change things as a workaround.

**Comment by oech3** [comment]
>It really is debatable whether --text, --binary is useful at all,

Another option is declareing (ignored) at GNU/uutils `cksum` before releasing next version and cleaning code for both project.

**Comment by RenjiSann** [comment]
Yes, I agree we could just ignore it 👍 Will do unless someone convince me otherwise

**Comment by sylvestre** [comment]
please do :)

**Comment by cakebaker** [comment]
Fixed by https://github.com/uutils/coreutils/pull/9695

**Comment by oech3** [comment]
```
$ hashsum --help
...
Options:
  -b, --binary          read in binary mode
...
  -t, --text            read in text mode (default) # <---????????
```

**Comment by oech3** [comment]
https://github.com/uutils/coreutils/blob/c96b96e233b007ea8c6c4b72029d6e5c4d655b6c/src/uu/cksum/src/cksum.rs#L309

It seems we are not hiding `--text` correctly. `--help` still show it.
